### ISSUE TITLE
ImportError: No module named pyreadline

### ISSUE THREAD

**Issue by young9471** [w3h/isf#1]
Hi Bro, I have some trouble in installing isf,can you help me? I install it on ubuntu 14.04 and there are something wrong with it .My problem  is just as follow :
young@ubuntu:~/ISF/isf$ python isf.py
Traceback (most recent call last):
  File "isf.py", line 9, in <module>
    from core.fuzzbunch import Fuzzbunch
  File "/home/young/ISF/isf/core/fuzzbunch.py", line 11, in <module>
    from command     import FbCmd
  File "/home/young/ISF/isf/core/command.py", line 22, in <module>
    import pyreadline as readline
ImportError: No module named pyreadline

**Comment by w3h** [comment]
please install gnureadline. the commond is pip install gnureadline

**Comment by w3h** [comment]
the pip version of default ubuntu  is lower. you need update pip. 
**sudo easy_install pip**

then install  gnureadline
**pip install gnureadline**

**Comment by young9471** [comment]
thank you
