### ISSUE TITLE
System or dependence problem

### ISSUE THREAD

**Issue by Dull-ar** [w3h/isf#5]
Hi Bro, I have some trouble in installing isf,can you help me? I install it on kali  and there are something wrong with it .My problem is just as follow :
Traceback (most recent call last):
  File "/home/kali/Desktop/isf-master/isf.py", line 10, in <module>
    from core.fuzzbunch import Fuzzbunch
  File "/home/kali/Desktop/isf-master/core/fuzzbunch.py", line 11, in <module>
    from command     import FbCmd
  File "/home/kali/Desktop/isf-master/core/command.py", line 22, in <module>
    import pyreadline as readline
  File "/home/kali/Desktop/isf-master/lib/thirdparty/pyreadline/__init__.py", line 14, in <module>
    raise RuntimeError('pyreadline is for Windows only, not {}.'.format(_S))
RuntimeError: pyreadline is for Windows only, not Linux.

**Comment by Amalll-Sec** [comment]
Hey bro, try to install gnureadline, like "pip2 install gnureadline".
